### ISSUE TITLE
Expresión bolivarcoin al inicio de las direcciones boli

### ISSUE THREAD

**Issue by camarjhoa** [BOLI-Project/AndroidWallet#5]
En el monedero android bolicoin, cada vez que se solicita una dirección boli para depósito y al pinchar el icono copiar o compartir se copia en el portapapeles o se comparte la dirección bolicoin; sin embargo, siempre antecede la palabra bolivarcoin:, lo cual hace que la persona que recibe la dirección de pago debe seleccionar solo la dirección, pudiendo ocasionar que  si algún usuario copia la dirección completa incluyendo la frase seguida de los dos puntos pueda hacer un envío inválido, por lo tanto pueda perder sus fondos, teniendo por sobreentendido que la frase bolivarcoin es para que el usuario sepa que es una dirección bolivarcoin. Por consiguiente, sugiero la posibilidad de eliminar de la billetera la palabra "bolivarcoin:"

**Comment by Visionario** [comment]
Sugerencia aceptada. Se tomarán las acciones para una actualización posterior.
Gracias por la observación.

FYI: La razón de ese comportamiento es para evitar que cuando se "pegue" en la misma aplicación o en la aplicación de otro usuario la dirección que colocas (antecedida por "bolivarcoin:") es para que la misma APP determine que la dirección pertenece a la Blockchain Bolivarcoin y no a alguna de las otras monedas y eso es debido a que nuestra aplicación de android es multimoneda y en ese caso la mas parecida es la de bitcoin.

Dicho esto, supongamos que copias de la moneda bolivarcoin la dirección _bHaLvUQNx4tDzDUMBB5v9mgYeekR8tgYsX_ sin el prefijo que mencionas "bolivarcoin:" y por error lo "pegas" teniendo abierta la moneda "bitcoin", (al contrario también es posible) esta será aceptada ya que ambas direcciones son válidas en las dos cadenas de bloque y esa es la razón de existir de ese comportamiento.

Puedo colocar también un ejemplo pasado con la antigua moneda _Arepacoin_ que por un comportamiento similar esa cadena podía validar direcciones de Bolivarcoin como si fueran de Arepacoin, tal y como fue reportado en este issue de _Arepacoin Project_ ["validateaddress" is validating Bolivarcoin addresses and permits sending](https://github.com/ProjectArepa/ArepaCoin/issues/1)

Para esta situación también se está estudiando entre los desarrolladores eliminar completamente el soporte multimoneda para dejar única y exclusivamente Bolicoin/Bolivarcoin.
